"""
Alembic env.py for a HexCore project.

This is the highest-value file in the framework to get right, because getting it wrong does
not raise. A table that exists in the database and is missing from `Base.metadata` gets an
`op.drop_table` in the next autogenerated migration -- the migration is generated cleanly, and
the damage appears when it is applied, in whatever environment runs it first.

Three calls prevent that, and all three are below. Do not delete one because the project does
not use that feature *yet*.
"""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from hexcore.config import LazyConfig
from hexcore.sql import Base, ensure_framework_models_loaded, import_all_models

# Replace with your own models package. `import_all_models` walks it recursively, so
# subpackages do not need listing.
import myapp.infrastructure.database.models as models

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


# ---- The three calls -------------------------------------------------------------

# 1. The tables HexCore itself declares: hexcore_cron_jobs, and the event store when you use
#    it. Without this they are outside Base.metadata and --autogenerate drops them.
ensure_framework_models_loaded()

# 2. Darwin's tables, plus every plugin's. Fill DARWIN_PLUGINS in with the plugins you
#    actually mount -- `hexcore identity plugins <your module>` prints the exact list.
#
#    Wrapped in try/except so a project without the [darwin] extra is not broken by it. With
#    Darwin, the table --autogenerate would drop here is the entire credential store.
DARWIN_PLUGINS: list[str] = []

try:
    from hexcore.darwin import ensure_identity_schema_loaded

    ensure_identity_schema_loaded(plugins=DARWIN_PLUGINS)
except ImportError:
    pass

# 3. Yours, recursively.
import_all_models(models)


target_metadata = Base.metadata

# The SYNCHRONOUS DSN. Alembic runs migrations synchronously; the app runs asynchronously,
# which is why ServerConfig carries both and they are not redundant.
config.set_main_option("sqlalchemy.url", LazyConfig().get_config().sql_database_url)


# ---- Standard Alembic wiring -----------------------------------------------------


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
